name: pin_keypad
description: Flutter package with beautiful keypad input, usable for PIN code input
version: 1.0.0
homepage: https://github.com/lepsi-city/pin_keypad

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: